### PR TITLE
Add Windows support

### PR DESCRIPTION
**Pull request by Lucasmaia435**

### CODE REVIEW

**Comment by elliejs** [comment]
does this work on windows 11 as well?

**Comment by Lucasmaia435** [comment]
> does this work on windows 11 as well?

Probably yes, but I've tested only on windows 10

**Comment by elliejs** [comment]
I kind of doubt it, WMIC has changed in windows 11. It's why I haven't implemented this solution. I'd love a solution which uses the lockfile.

**Comment by Lucasmaia435** [comment]
> I kind of doubt it, WMIC has changed in windows 11. It's why I haven't implemented this solution. I'd love a solution which uses the lockfile.

@elliejs I read more about WMIC, and removed the solution with it. Now I implemented using the lockfile.

**Comment by Lucasmaia435** [comment]
@elliejs

**Pull request closed without merging**
